### PR TITLE
[INLONG-1852] The Master of TubeMQ supports monitoring indicators with JMX

### LINKED ISSUE #1852: The Master of TubeMQ supports monitoring indicators with JMX.
### Description

The requirement see https://github.com/apache/incubator-inlong/issues/1851

For the Master module, judging from the current problem positioning, the following content needs to be supported:
1. consume_group_cnt number of consumer groups
2. The current number of producers in producer_cnt
3. broker_configure_cnt broker configuration number
4. Broker_online_cnt broker online number
5. The number of broker_abnormal_cnt broker exceptions
6. broker_timeout_count total number of broker timeouts
7. broker_timeout_avg broker average timeout per minute
8. balance_clt_cnt The number of consumer groups balanced by the client
9. balance_svr_cnt The number of balanced consumer groups on the server
10. balance_svr_latency_avg server-side balance average duration
11. balance_svr_latency_max server-side balance is the largest
12. balance_reset_ready_latency_avg The average completion time for the server to reset the Offset balance
13. balance_reset_ready_latency_max The maximum completion time for the server to reset the Offset balance

This involves some existing data statistical conversion, we will uniformly use the JMX method for processing

### Use case

_No response_

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by gosonzhang**
Fixes #1852

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

**Comment by dockerzhang** [comment]
@gosonzhang please add a guiding document after this PR merged.

**Review by aloyszhang — APPROVED** [review]
LGTM

**Review by healchow — APPROVED** [review]
+1

**Comment by gosonzhang** [comment]
@dockerzhang, I’m still working on the Broker’s metrics, and I will submit the documents after this sub-issue is completed.

**Pull request merged**
