### PR TITLE
[INLONG-3504][Manager] upgrade to jackson without cve

### LINKED ISSUE #3504: [Bug] upgrade to jackson-databind 2.12.6.1 (due to cve)
### What happened

dependabot alert

https://github.com/advisories/GHSA-57j2-w4cx-62h2

only jackson-databind has a 2.12.6.1 release - other jackson jars should be upgraded to 2.12.6

### What you expected to happen

n/a

### How to reproduce

n/a

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #3534: [Improve] Update the dependency by dependabot
### Description

Update the dependency by dependabot

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pjfanning**
Fixes #3504

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by healchow** [comment]
I will make a check on my local environment.

**Review by EMsnap — APPROVED** [review]

**Comment by dockerzhang** [comment]
@pjfanning do we need an update to `2.13.2.1` refers to https://github.com/apache/incubator-inlong/pull/3585?

**Comment by dockerzhang** [comment]
https://github.com/apache/incubator-inlong/pull/3584 please bump postgresql from 42.2.25 to 42.3.3 at the same time, thanks.

**Comment by pjfanning** [comment]
@dockerzhang 2.12.6.1 has the same fix as 2.13.2.1

**Review by healchow — APPROVED** [review]

**Pull request merged**
