### PR TITLE
[INLONG-1593][checkstyle] Add EmptyLineSeparator java code checkstyle rule

### LINKED ISSUE #1593: Add EmptyLineSeparator java code checkstyle rule
**Is your feature request related to a problem? Please describe.**

There are some empty lines in current codebase, maybe two empty lines or three empty lines.
It's better to checks for empty line separator between tokens, and make them keep the style consistent.

**Describe the solution you'd like**
Add EmptyLineSeparator java code checkstyle rule.

### PR DESCRIPTION
**Pull request by leo65535**
Fixes #1593

### Motivation

There are some empty lines in current codebase, maybe two empty lines or three empty lines.
It's better to checks for empty line separator between tokens, and make them keep the style consistent.

### Modifications

Add EmptyLineSeparator java code checkstyle rule.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by aloyszhang** [comment]
LGTM，let's wait the CI pass.

**Comment by leo65535** [comment]
Thanks you all, seems the mvn repo center is instable.
```
Error:  Failed to execute goal on project tubemq-manager: Could not resolve dependencies for project org.apache.inlong:tubemq-manager:jar:0.11.0-incubating-SNAPSHOT: The following artifacts could not be resolved: org.springframework.boot:spring-boot-starter-web:jar:2.3.3.RELEASE, org.springframework.boot:spring-boot:jar:2.3.3.RELEASE, org.springframework.boot:spring-boot-autoconfigure:jar:2.3.3.RELEASE: Could not transfer artifact org.springframework.boot:spring-boot-starter-web:jar:2.3.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-web/2.3.3.RELEASE/spring-boot-starter-web-2.3.3.RELEASE.jar: Connection timed out (Read failed) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project tubemq-manager: Could not resolve dependencies for project org.apache.inlong:tubemq-manager:jar:0.11.0-incubating-SNAPSHOT: The following artifacts could not be resolved: org.springframework.boot:spring-boot-starter-web:jar:2.3.3.RELEASE, org.springframework.boot:spring-boot:jar:2.3.3.RELEASE, org.springframework.boot:spring-boot-autoconfigure:jar:2.3.3.RELEASE: Could not transfer artifact org.springframework.boot:spring-boot-starter-web:jar:2.3.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-web/2.3.3.RELEASE/spring-boot-starter-web-2.3.3.RELEASE.jar
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:269)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:248)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:202)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
```

**Comment by aloyszhang** [comment]
@leo65535 I've re-run the failure check.

**Review by aloyszhang — APPROVED** [review]
+1

**Review by dockerzhang — APPROVED** [review]
+1

**Pull request merged**
