### PR TITLE
[INLONG-2596][TubeMQ] fix param error and add override annotation

### LINKED ISSUE #2596: [Improve] fix param in the client module and  the main class of tubeManager pom is error
### Description

the param is spelling error,so i fix it.
And the main class of  tubeManager pom is error.
so I fix it at the same time.

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yimaixinchen**
fix param error and add override annotation
I think it is easy to be merged

fix #2596

### CODE REVIEW

**Comment by yimaixinchen** [comment]
I create the issue.
https://github.com/apache/incubator-inlong/issues/2596
@dockerzhang 
Please relate to the issue.

**Comment by yimaixinchen** [comment]
If the issue is not standard,please be patient and guide me how to do.
Thanks.

**Comment by dockerzhang** [comment]
@EMsnap @gosonzhang PTAL

**Review by gosonzhang — APPROVED** [review]

**Comment by dockerzhang** [comment]
@yimaixinchen thanks for your contribution for #2596, there are lots of tasks you could do if you are interested in the [issue list](https://github.com/apache/incubator-inlong/issues), look for your forward PRs.

**Pull request merged**
