### PR TITLE
[INLONG-1798] RestTemplate does not read configuration from the configuration file.

### PR DESCRIPTION
**Pull request by GRAYCELL-ZHOU**
Modify the RestTemplate to read the configuration from the configuration file.

### CODE REVIEW

**Comment by dockerzhang** [comment]
@GRAYCELL-ZHOU Please add "fix #1798" to relate the issue for this PR, and change the target branch to `master`.

**Review by gosonzhang — APPROVED** [review]
+1

**Comment by gosonzhang** [comment]
@GRAYCELL-ZHOU, I see that this feature is merged in version 0.11.0. Does the problem also exist on the master branch? Can you mention another PR to the master?

**Comment by GRAYCELL-ZHOU** [comment]
ok

**Pull request merged**
