### PR TITLE
[INLONG-2064] tubemq-manager TopicEntry.java:[28,36] package javax.validation.constraints not exists

### LINKED ISSUE #2064: [Bug]master branch, tubemq-manager  module occurs: package Java.validation.constraints not exists
### What happened

image

### What you expected to happen

javax.validation:validation-api isn't imported in tubemq-manager module.

### How to reproduce

1. git clone git@github.com:apache/incubator-inlong.git
2. git checkout master
3. maven clean install -DskipTests

### Environment

_No response_

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liaorui**
### Title Name: [INLONG-2064][tubemq-manager] solved: tubemq-manager TopicEntry.java:[28,36] package javax.validation.constraints not exists

Fixes #2064

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by dockerzhang** [comment]
@gosonzhang PTAL

**Comment by EMsnap** [comment]
LGTM

**Review by EMsnap — APPROVED** [review]
lgtm

**Review by dockerzhang — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]
+1

**Comment by gosonzhang** [comment]
@liaorui, thanks for your contribution!

**Pull request merged**
