### PR TITLE
[INlONG-2791][Manager] Optimize manager client APIs

### LINKED ISSUE #2791: [Improve] Optimize manager client apis
### Description

_No response_

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kipshi**
### Title Name: [INlONG-2791] Optimize Inlong manager client apis

where *XYZ* should be replaced by the actual issue number.

Fixes #2791 

### Motivation

optimize methods in client

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by healchow — APPROVED** [review]
LGTM

**Review by healchow — APPROVED** [review]
LGTM

**Comment by gong** [comment]
only modify `SinkPageRequest` and `SourcePageRequest` will cause some problem.

StreamSinkServiceImpl
` public PageInfo<? extends SinkListResponse> listByCondition(SinkPageRequest request) {
        if (LOGGER.isDebugEnabled()) {
            LOGGER.debug("begin to list sink page by " + request);
        }
        Preconditions.checkNotNull(request.getInlongGroupId(), Constant.GROUP_ID_IS_EMPTY);
        String sinkType = request.getSinkType();
        Preconditions.checkNotNull(sinkType, Constant.SINK_TYPE_IS_EMPTY);`
StreamSourceServiceImpl
` public PageInfo<? extends SourceListResponse> listByCondition(SourcePageRequest request) {
        if (LOGGER.isDebugEnabled()) {
            LOGGER.debug("begin to list source page by " + request);
        }
        Preconditions.checkNotNull(request.getInlongGroupId(), Constant.GROUP_ID_IS_EMPTY);
        String sourceType = request.getSourceType();
        Preconditions.checkNotNull(sourceType, Constant.SOURCE_TYPE_IS_EMPTY);`

**Review by dockerzhang — APPROVED** [review]

**Review by ciscozhou — APPROVED** [review]
Cool.

**Pull request merged**
